
dataset: 
  tag: "WebQSP"
  train: "data/dataset/WebQSP/train_simple.jsonl"
  dev: "data/dataset/WebQSP/dev_simple.jsonl"
  test: "data/dataset/WebQSP/test_simple.jsonl"
  # follow the setting of using gold topic entities in Subgraph Retrieval 
  SR_cache_all: Null
  train_relations: "data/dataset/WebQSP/WebQSP_train_relations.json"
  test_iid_idxs: "data/dataset/WebQSP/WebQSP_test_iid_idxs.json"
  test_zero_shot_idxs: "data/dataset/WebQSP/WebQSP_test_zero_shot_idxs.json"

cache:
  pred_info: "data/cache/predicate_info_fb.json"
  type_info: "data/cache/type_info_fb.json"
  pred_conn: "data/cache/pred_conn_fb.jsonl"
  searched_path: "data/cache/WebQSP/cached_paths.jsonl"

log:
  process_log: "data/log/process.log"
  level: "DEBUG"

global_var:
  # by seconds
  query_time_limit: 1
  # n-ary fact with cvt node is considered one hop
  max_hop_limit: 1
  # control whether to perform heuristic path search in bulk (if "cache/searched_path" do not exists, set it to True)
  bulk_path_search: True
  # worker number of multi process
  worker_num: 5

ap_retrieval:
  # working directory
  work_dir: "data/WebQSP/lp_retrieval/"
  # pred-pred snippets topk
  ap_topk: 100

ep_generation:
  # working directory
  work_dir: "data/WebQSP/ep_generation/"
  # max combine count
  max_combine_preds: 3

ans_selection:
  work_dir: "data/WebQSP/ans_selection/"
  ep_topk: 1