
dataset: 
  tag: "CWQ"
  train: "data/dataset/CWQ/ComplexWebQuestions_train.json"
  dev: "data/dataset/CWQ/ComplexWebQuestions_dev.json"
  test: "data/dataset/CWQ/ComplexWebQuestions_test.json"
  # follow the setting of using gold topic entities in Subgraph Retrieval 
  SR_cache_all: "data/dataset/CWQ/CWQ_full_with_int_id.jsonl"

cache:
  searched_path: "data/cache/CWQ/cached_paths.jsonl"

log:
  process_log: "data/log/CWQ_process.log"
  level: "DEBUG"

global_var:
  # by seconds
  query_time_limit: 1
  # n-ary fact with cvt node is considered one hop
  max_hop_limit: 2 
  # control whether to perform heuristic path search in bulk (if "cache/searched_path" do not exists, set it to True)
  bulk_path_search: True
  # worker number of multi process
  worker_num: 4

ap_retrieval:
  # working directory
  work_dir: "data/CWQ/ap_retrieval/"
  # rel-rel aps topk
  ap_topk: 100

ep_retrieval:
  # working directory
  work_dir: "data/CWQ/ep_retrieval/"
  # max combine count
  max_combine_rels: 5

subgraph_extraction:
  work_dir: "data/CWQ/subgraph_extraction/"
  ep_topk: 1