
dataset: 
  tag: "CWQ"
  train: "data/dataset/CWQ/ComplexWebQuestions_train.json"
  dev: "data/dataset/CWQ/ComplexWebQuestions_dev.json"
  test: "data/dataset/CWQ/ComplexWebQuestions_test.json"
  # follow the setting of using gold topic entities in Subgraph Retrieval 
  SR_cache_all: "data/dataset/CWQ/CWQ_full_with_int_id.jsonl"
  train_relations: "data/dataset/CWQ/CWQ_train_relations.json"
  test_iid_idxs: "data/dataset/CWQ/CWQ_test_iid_idxs.json"
  test_zero_shot_idxs: "data/dataset/CWQ/CWQ_test_zero_shot_idxs.json"

cache:
  pred_info: "data/cache/predicate_info_fb.json"
  type_info: "data/cache/type_info_fb.json"
  searched_path: "data/cache/CWQ/cached_paths.jsonl"
  pred_conn: "data/cache/pred_conn_fb.jsonl"

log:
  process_log: "data/log/process.log"
  level: "DEBUG"

global_var:
  # by seconds
  query_time_limit: 1
  # n-ary fact with cvt node is considered one hop
  max_hop_limit: 2 
  # control whether to perform heuristic path search in bulk (if "cache/searched_path" do not exists, set it to True)
  bulk_path_search: True
  # worker number of multi process
  worker_num: 5

ap_retrieval:
  # working directory
  work_dir: "data/CWQ/lp_retrieval/"
  # pred-pred snippets topk
  ap_topk: 100

ep_generation:
  # working directory
  work_dir: "data/CWQ/ep_generation/"
  # max combine count
  max_combine_preds: 5

ans_selection:
  work_dir: "data/CWQ/ans_selection/"
  ep_topk: 1