
dataset: 
  tag: "WebQSP"
  # follow the setting of using gold topic entities in Subgraph Retrieval 
  train: "data/dataset/WebQSP/train_simple.jsonl"
  dev: "data/dataset/WebQSP/dev_simple.jsonl"
  test: "data/dataset/WebQSP/test_simple.jsonl"
  SR_cache_all: Null

cache:
  searched_path: "data/cache/WebQSP/cached_paths.jsonl"

log:
  process_log: "data/log/WebQSP_process.log"
  level: "DEBUG"

global_var:
  # by seconds
  query_time_limit: 1
  # n-ary fact with cvt node is considered one hop
  max_hop_limit: 1
  # control whether to perform heuristic path search in bulk (if "cache/searched_path" do not exists, set it to True)
  bulk_path_search: True
  # worker number of multi process
  worker_num: 6

ap_retrieval:
  # working directory
  work_dir: "data/WebQSP/ap_retrieval/"
  # rel-rel aps topk
  ap_topk: 100

ep_generation:
  # working directory
  work_dir: "data/WebQSP/ep_generation/"
  # max combine count
  max_combine_rels: 3

subgraph_extraction:
  work_dir: "data/WebQSP/subgraph_extraction/"
  ep_topk: 1